Deploy scripts
golemfactory/gwasm-tutorial pull request #3
Opened 2019-10-01 10:49 UTC by nieznanysprawiciel

2019-10-02 07:45 UTC, tworec requested changes

2019-10-02 07:45 UTC, tworec commented on build-image.sh
> +./../prepare-git-repo.sh key_cracker_gen
pls remove it. `key_cracker_gen` is on internal use only.

2019-10-02 07:52 UTC, tworec commented
@prekucki or @nieznanysprawiciel pls add here @mbenke PR
https://github.com/prekucki/gwasm-tutorial/pull/3

2019-10-02 08:16 UTC, tworec commented on build-image.sh
> +./../prepare-git-repo.sh key_cracker_demo
```suggestion
./../prepare-git-repo.sh key_cracker_rust
```
pls rename it to `_rust` as opossite to `_cpp`.
Whats more, there is contents of this repo duplicated within itself
```
root@d174bcaa9dda:~/key_cracker_cpp# ls -o
total 28
-rw-r--r-- 1 root   96 Oct  1 09:41 CMakeLists.txt
-rw-r--r-- 1 root   18 Oct  1 09:41 README.md
drwxr-xr-x 2 root 4096 Oct  1 10:39 bin
drwxr-xr-x 5 root 4096 Oct  1 10:39 build
drwxr-xr-x 4 root 4096 Oct  1 09:41 include
drwxr-xr-x 5 root 4096 Oct  1 09:52 key_cracker_cpp
drwxr-xr-x 2 root 4096 Oct  1 09:41 src
root@d174bcaa9dda:~/key_cracker_cpp# ls -o key_cracker_cpp/
total 16
-rw-r--r-- 1 root   96 Oct  1 09:52 CMakeLists.txt
-rw-r--r-- 1 root   18 Oct  1 09:52 README.md
drwxr-xr-x 4 root 4096 Oct  1 09:52 include
drwxr-xr-x 2 root 4096 Oct  1 09:52 src
```

And README.txt is empty....
Please at least copy wiki to README.txt
https://github.com/golemfactory/key_cracker_cpp/wiki

2019-10-02 08:36 UTC, tworec commented
Also pls add welcome msg for the docker
https://docs.google.com/document/d/19ROy9z5dNWexGeyxErGwnaPkl575J07_6ZBM6WTzRGs/edit

2019-10-02 13:02 UTC, nieznanysprawiciel commented
All requested changes will be apllyed in this PR:
https://github.com/golemfactory/gwasm-tutorial/pull/4

2019-10-04 12:14 UTC, tworec commented
> All requested changes will be apllyed in this PR:
> #4

so I'm closing this one

2019-10-04 12:14 UTC, closed without merging